  let timelineElements = [
  {
    id: 1,
    date: "November 30th, 2023",
    stream: "TDX",
    description:
      "Sam / Andrew 1:1",
    buttonText: "View Frontend Projects",
    icon: "work",
  },
  {
    id: 2,
    date: "November 26th, 2023",
    stream: "MSE",
    description:
      "MSE | All Hands",
    buttonText: "View Backend Projects",
    icon: "work",
  },
  {
    id: 3,
    date: "November 21st, 2023",
    stream: "Personal",
    description:
      "Deer Butchering Course",
    buttonText: "Company Website",
    icon: "work",
  },
  {
    id: 4,
    date: "November 21st, 2023",
    stream: "Personal",
    description:
      "Deer Butchering Course",
    buttonText: "Company Website",
    icon: "work",
  },
  {
    id: 5,
    date: "November 21st, 2023",
    stream: "Personal",
    description:
      "Deer Butchering Course",
    buttonText: "Company Website",
    icon: "work",
  },
  {
    id: 6,
    date: "November 21st, 2023",
    stream: "Personal",
    description:
      "Deer Butchering Course",
    buttonText: "Company Website",
    icon: "work",
  },
  {
    id: 7,
    date: "November 15th, 2023",
    stream: "XYZ",
    description: "XYZ Quarterly Review",
    buttonText: "View More",
    icon: "work",
  },
  {
    id: 8,
    date: "November 10th, 2023",
    stream: "ABC",
    description: "Team Building Activity",
    buttonText: "Event Details",
    icon: "work",
  },
  {
    id: 9,
    date: "November 5th, 2023",
    stream: "DEF",
    description: "DEF Product Launch",
    buttonText: "Product Info",
    icon: "work",
  },
  {
    id: 10,
    date: "October 31st, 2023",
    stream: "GHI",
    description: "Halloween Party",
    buttonText: "Party Photos",
    icon: "work",
  },
  // Continuing in a similar pattern...
  {
    id: 11,
    date: "December 1st, 2023",
    stream: "JKL",
    description: "Company Meeting",
    buttonText: "Meeting Agenda",
    icon: "work",
  },
  {
    id: 12,
    date: "December 5th, 2023",
    stream: "MNO",
    description: "MNO Product Update",
    buttonText: "Product Release Notes",
    icon: "work",
  },
  {
    id: 13,
    date: "December 10th, 2023",
    stream: "PQR",
    description: "Team Training Session",
    buttonText: "Training Materials",
    icon: "work",
  },
  {
    id: 14,
    date: "December 20th, 2023",
    stream: "STU",
    description: "Holiday Celebration",
    buttonText: "Holiday Photos",
    icon: "work",
  },
  {
    id: 15,
    date: "December 25th, 2023",
    stream: "VWX",
    description: "Christmas Party",
    buttonText: "Party Highlights",
    icon: "work",
  },
  {
    id: 16,
    date: "December 31st, 2023",
    stream: "YZA",
    description: "New Year's Eve Party",
    buttonText: "New Year's Countdown",
    icon: "work",
  },
  {
    id: 17,
    date: "January 5th, 2024",
    stream: "BCD",
    description: "Project Kickoff",
    buttonText: "Project Details",
    icon: "work",
  },
  {
    id: 18,
    date: "January 10th, 2024",
    stream: "EFG",
    description: "EFG Conference",
    buttonText: "Conference Schedule",
    icon: "work",
  },
  {
    id: 19,
    date: "January 15th, 2024",
    stream: "HIJ",
    description: "HIJ Product Demo",
    buttonText: "Demo Video",
    icon: "work",
  },
  {
    id: 20,
    date: "January 20th, 2024",
    stream: "KLM",
    description: "Company Retreat",
    buttonText: "Retreat Itinerary",
    icon: "work",
  },
  {
    id: 21,
    date: "January 25th, 2024",
    stream: "NOP",
    description: "Team Building Workshop",
    buttonText: "Workshop Details",
    icon: "work",
  },
  {
    id: 22,
    date: "February 1st, 2024",
    stream: "QRS",
    description: "Project Review",
    buttonText: "Review Summary",
    icon: "work",
  },
  {
    id: 23,
    date: "February 5th, 2024",
    stream: "TUV",
    description: "TUV Product Launch",
    buttonText: "Product Info",
    icon: "work",
  },
  {
    id: 24,
    date: "February 10th, 2024",
    stream: "XYZ",
    description: "XYZ Team Building Event",
    buttonText: "Event Photos",
    icon: "work",
  },
  {
    id: 25,
    date: "February 15th, 2024",
    stream: "ABC",
    description: "ABC Conference",
    buttonText: "Conference Agenda",
    icon: "work",
  },
  {
    id: 26,
    date: "February 20th, 2024",
    stream: "DEF",
    description: "DEF Product Demo",
    buttonText: "Demo Video",
    icon: "work",
  },
  {
    id: 27,
    date: "February 25th, 2024",
    stream: "GHI",
    description: "Team Training Session",
    buttonText: "Training Materials",
    icon: "work",
  },
  {
    id: 28,
    date: "March 1st, 2024",
    stream: "JKL",
    description: "Company Meeting",
    buttonText: "Meeting Agenda",
    icon: "work",
  },
  {
    id: 29,
    date: "March 5th, 2024",
    stream: "MNO",
    description: "MNO Product Update",
    buttonText: "Product Release Notes",
    icon: "work",
  },
  {
    id: 30,
    date: "March 10th, 2024",
    stream: "PQR",
    description: "Team Building Workshop",
    buttonText: "Workshop Details",
    icon: "work",
  },
  {
    id: 31,
    date: "March 15th, 2024",
    stream: "STU",
    description: "STU Product Launch",
    buttonText: "Product Info",
    icon: "work",
  },
  {
    id: 32,
    date: "March 20th, 2024",
    stream: "VWX",
    description: "Company Retreat",
    buttonText: "Retreat Itinerary",
    icon: "work",
  },
  {
    id: 33,
    date: "March 25th, 2024",
    stream: "YZA",
    description: "Project Kickoff",
    buttonText: "Project Details",
    icon: "work",
  },
  {
    id: 34,
    date: "March 30th, 2024",
    stream: "BCD",
    description: "BCD Conference",
    buttonText: "Conference Schedule",
    icon: "work",
  },
  {
    id: 35,
    date: "April 5th, 2024",
    stream: "EFG",
    description: "EFG Product Demo",
    buttonText: "Demo Video",
    icon: "work",
  },
  {
    id: 36,
    date: "April 10th, 2024",
    stream: "HIJ",
    description: "HIJ Team Building Event",
    buttonText: "Event Photos",
    icon: "work",
  },
  {
    id: 37,
    date: "April 15th, 2024",
    stream: "KLM",
    description: "Company Meeting",
    buttonText: "Meeting Agenda",
    icon: "work",
  },
  {
    id: 38,
    date: "April 20th, 2024",
    stream: "NOP",
    description: "NOP Product Update",
    buttonText: "Product Release Notes",
    icon: "work",
  },
  {
    id: 39,
    date: "April 25th, 2024",
    stream: "QRS",
    description: "Team Training Session",
    buttonText: "Training Materials",
    icon: "work",
  },
  {
    id: 40,
    date: "April 30th, 2024",
    stream: "TUV",
    description: "TUV Product Launch",
    buttonText: "Product Info",
    icon: "work",
  },
  {
  id: 41,
  date: "May 5th, 2024",
  stream: "UVW",
  description: "UVW Product Demo",
  buttonText: "Demo Video",
  icon: "work",
  },
  {
  id: 42,
  date: "May 10th, 2024",
  stream: "XYZ",
  description: "XYZ Team Building Event",
  buttonText: "Event Photos",
  icon: "work",
  },
  {
  id: 43,
  date: "May 15th, 2024",
  stream: "ABC",
  description: "ABC Conference",
  buttonText: "Conference Agenda",
  icon: "work",
  },
  {
  id: 44,
  date: "May 20th, 2024",
  stream: "DEF",
  description: "DEF Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 45,
  date: "May 25th, 2024",
  stream: "GHI",
  description: "Team Training Session",
  buttonText: "Training Materials",
  icon: "work",
  },
  {
  id: 46,
  date: "June 1st, 2024",
  stream: "JKL",
  description: "Company Meeting",
  buttonText: "Meeting Agenda",
  icon: "work",
  },
  {
  id: 47,
  date: "June 5th, 2024",
  stream: "MNO",
  description: "MNO Product Update",
  buttonText: "Product Release Notes",
  icon: "work",
  },
  {
  id: 48,
  date: "June 10th, 2024",
  stream: "PQR",
  description: "Team Building Workshop",
  buttonText: "Workshop Details",
  icon: "work",
  },
  {
  id: 49,
  date: "June 15th, 2024",
  stream: "STU",
  description: "STU Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 50,
  date: "June 20th, 2024",
  stream: "VWX",
  description: "Company Retreat",
  buttonText: "Retreat Itinerary",
  icon: "work",
  },
  {
  id: 51,
  date: "June 25th, 2024",
  stream: "YZA",
  description: "Project Kickoff",
  buttonText: "Project Details",
  icon: "work",
  },
  {
  id: 52,
  date: "June 30th, 2024",
  stream: "BCD",
  description: "BCD Conference",
  buttonText: "Conference Schedule",
  icon: "work",
  },
  {
  id: 53,
  date: "July 5th, 2024",
  stream: "EFG",
  description: "EFG Product Demo",
  buttonText: "Demo Video",
  icon: "work",
  },
  {
  id: 54,
  date: "July 10th, 2024",
  stream: "HIJ",
  description: "HIJ Team Building Event",
  buttonText: "Event Photos",
  icon: "work",
  },
  {
  id: 55,
  date: "July 15th, 2024",
  stream: "KLM",
  description: "Company Meeting",
  buttonText: "Meeting Agenda",
  icon: "work",
  },
  {
  id: 56,
  date: "July 20th, 2024",
  stream: "NOP",
  description: "NOP Product Update",
  buttonText: "Product Release Notes",
  icon: "work",
  },
  {
  id: 57,
  date: "July 25th, 2024",
  stream: "QRS",
  description: "Team Training Session",
  buttonText: "Training Materials",
  icon: "work",
  },
  {
  id: 58,
  date: "July 30th, 2024",
  stream: "TUV",
  description: "TUV Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 59,
  date: "August 5th, 2024",
  stream: "UVW",
  description: "UVW Product Demo",
  buttonText: "Demo Video",
  icon: "work",
  },
  {
  id: 60,
  date: "August 10th, 2024",
  stream: "XYZ",
  description: "XYZ Team Building Event",
  buttonText: "Event Photos",
  icon: "work",
  },
  {
  id: 61,
  date: "August 15th, 2024",
  stream: "ABC",
  description: "ABC Conference",
  buttonText: "Conference Agenda",
  icon: "work",
  },
  {
  id: 62,
  date: "August 20th, 2024",
  stream: "DEF",
  description: "DEF Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 63,
  date: "August 25th, 2024",
  stream: "GHI",
  description: "Team Training Session",
  buttonText: "Training Materials",
  icon: "work",
  },
  {
  id: 64,
  date: "September 1st, 2024",
  stream: "JKL",
  description: "Company Meeting",
  buttonText: "Meeting Agenda",
  icon: "work",
  },
  {
  id: 65,
  date: "September 5th, 2024",
  stream: "MNO",
  description: "MNO Product Update",
  buttonText: "Product Release Notes",
  icon: "work",
  },
  {
  id: 66,
  date: "September 10th, 2024",
  stream: "PQR",
  description: "Team Building Workshop",
  buttonText: "Workshop Details",
  icon: "work",
  },
  {
  id: 67,
  date: "September 15th, 2024",
  stream: "STU",
  description: "STU Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 68,
  date: "September 20th, 2024",
  stream: "VWX",
  description: "Company Retreat",
  buttonText: "Retreat Itinerary",
  icon: "work",
  },
  {
  id: 69,
  date: "September 25th, 2024",
  stream: "YZA",
  description: "Project Kickoff",
  buttonText: "Project Details",
  icon: "work",
  },
  {
  id: 70,
  date: "September 30th, 2024",
  stream: "BCD",
  description: "BCD Conference",
  buttonText: "Conference Schedule",
  icon: "work",
  },
  {
  id: 71,
  date: "October 5th, 2024",
  stream: "EFG",
  description: "EFG Product Demo",
  buttonText: "Demo Video",
  icon: "work",
  },
  {
  id: 72,
  date: "October 10th, 2024",
  stream: "HIJ",
  description: "HIJ Team Building Event",
  buttonText: "Event Photos",
  icon: "work",
  },
  {
  id: 73,
  date: "October 15th, 2024",
  stream: "KLM",
  description: "Company Meeting",
  buttonText: "Meeting Agenda",
  icon: "work",
  },
  {
  id: 74,
  date: "October 20th, 2024",
  stream: "NOP",
  description: "NOP Product Update",
  buttonText: "Product Release Notes",
  icon: "work",
  },
  {
  id: 75,
  date: "October 25th, 2024",
  stream: "QRS",
  description: "Team Training Session",
  buttonText: "Training Materials",
  icon: "work",
  },
  {
  id: 76,
  date: "October 30th, 2024",
  stream: "TUV",
  description: "TUV Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 77,
  date: "November 5th, 2024",
  stream: "UVW",
  description: "UVW Product Demo",
  buttonText: "Demo Video",
  icon: "work",
  },
  {
  id: 78,
  date: "November 10th, 2024",
  stream: "XYZ",
  description: "XYZ Team Building Event",
  buttonText: "Event Photos",
  icon: "work",
  },
  {
  id: 79,
  date: "November 15th, 2024",
  stream: "ABC",
  description: "ABC Conference",
  buttonText: "Conference Agenda",
  icon: "work",
  },
  {
  id: 80,
  date: "November 20th, 2024",
  stream: "DEF",
  description: "DEF Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 81,
  date: "December 5th, 2024",
  stream: "GHI",
  description: "Team Training Session",
  buttonText: "Training Materials",
  icon: "work",
  },
  {
  id: 82,
  date: "December 10th, 2024",
  stream: "JKL",
  description: "Company Meeting",
  buttonText: "Meeting Agenda",
  icon: "work",
  },
  {
  id: 83,
  date: "December 15th, 2024",
  stream: "MNO",
  description: "MNO Product Update",
  buttonText: "Product Release Notes",
  icon: "work",
  },
  {
  id: 84,
  date: "December 20th, 2024",
  stream: "PQR",
  description: "Team Building Workshop",
  buttonText: "Workshop Details",
  icon: "work",
  },
  {
  id: 85,
  date: "December 25th, 2024",
  stream: "STU",
  description: "STU Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 86,
  date: "December 30th, 2024",
  stream: "VWX",
  description: "Company Retreat",
  buttonText: "Retreat Itinerary",
  icon: "work",
  },
  {
  id: 87,
  date: "January 5th, 2025",
  stream: "YZA",
  description: "Project Kickoff",
  buttonText: "Project Details",
  icon: "work",
  },
  {
  id: 88,
  date: "January 10th, 2025",
  stream: "BCD",
  description: "BCD Conference",
  buttonText: "Conference Schedule",
  icon: "work",
  },
  {
  id: 89,
  date: "January 15th, 2025",
  stream: "EFG",
  description: "EFG Product Demo",
  buttonText: "Demo Video",
  icon: "work",
  },
  {
  id: 90,
  date: "January 20th, 2025",
  stream: "HIJ",
  description: "HIJ Team Building Event",
  buttonText: "Event Photos",
  icon: "work",
  },
  {
  id: 91,
  date: "January 25th, 2025",
  stream: "KLM",
  description: "Company Meeting",
  buttonText: "Meeting Agenda",
  icon: "work",
  },
  {
  id: 92,
  date: "January 30th, 2025",
  stream: "NOP",
  description: "NOP Product Update",
  buttonText: "Product Release Notes",
  icon: "work",
  },
  {
  id: 93,
  date: "February 5th, 2025",
  stream: "QRS",
  description: "Team Training Session",
  buttonText: "Training Materials",
  icon: "work",
  },
  {
  id: 94,
  date: "February 10th, 2025",
  stream: "TUV",
  description: "TUV Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 95,
  date: "February 15th, 2025",
  stream: "UVW",
  description: "UVW Product Demo",
  buttonText: "Demo Video",
  icon: "work",
  },
  {
  id: 96,
  date: "February 20th, 2025",
  stream: "XYZ",
  description: "XYZ Team Building Event",
  buttonText: "Event Photos",
  icon: "work",
  },
  {
  id: 97,
  date: "February 25th, 2025",
  stream: "ABC",
  description: "ABC Conference",
  buttonText: "Conference Agenda",
  icon: "work",
  },
  {
  id: 98,
  date: "March 1st, 2025",
  stream: "DEF",
  description: "DEF Product Launch",
  buttonText: "Product Info",
  icon: "work",
  },
  {
  id: 99,
  date: "March 5th, 2025",
  stream: "GHI",
  description: "Team Training Session",
  buttonText: "Training Materials",
  icon: "work",
  },
  {
  id: 100,
  date: "March 10th, 2025",
  stream: "JKL",
  description: "Company Meeting",
  buttonText: "Meeting Agenda",
  icon: "work",
  },
];

export default timelineElements;
